#!/bin/sh /etc/rc.common
USE_PROCD=1
START=100
STOP=10

BOT_DIR="/opt/tgbot"

start_service() {
    procd_open_instance "tgbot"
    procd_set_param command python3 /opt/tgbot/bot.py
    procd_set_param env PYTHONPATH=/opt/tgbot
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_set_param respawn 300 5 0
    procd_close_instance

    procd_open_instance "setup"
    procd_set_param command python3 /opt/tgbot/setup_server.py
    procd_set_param env PYTHONPATH=/opt/tgbot
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_set_param respawn 300 5 0
    procd_close_instance
}
